parameters:
    stripe_secret_key: 'sk_test_51PaPFUBrJ9scVcZ138I70EsKRXB8prbjn2qQXgHeC7AMEUOhbOGUzbTm09pejA2ezQh3LOhTG5CnYq1PXEcAly9P00THC1XL4o'
    stripe_public_key: 'pk_test_51PaPFUBrJ9scVcZ19MjkhxCMMRQphbn47M2KYIwoHaSiwt6xiPQTi2Pzs9ac3k2XfLCbA0uxeVzssPbX6TeYjigO00DYfnqQI0'

services:
    App\Service\StripeService:
        arguments:
            $stripeSecretKey: '%stripe_secret_key%'
            $stripePublicKey: '%stripe_public_key%'
